import { ButtonHTMLAttributes, HTMLAttributes, ReactNode } from 'react'
import { cn } from '../lib/utils'

export function Button({ className, variant = 'default', size = 'md', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'default' | 'outline' | 'ghost' | 'danger'; size?: 'sm' | 'md' | 'lg' }) {
  return <button className={cn('inline-flex items-center justify-center gap-2 font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand/40 disabled:pointer-events-none disabled:opacity-50', variant === 'default' && 'bg-ink text-white hover:bg-ink/90', variant === 'outline' && 'border border-line bg-white text-ink hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:hover:bg-slate-800', variant === 'ghost' && 'text-muted hover:bg-slate-100 hover:text-ink dark:hover:bg-slate-800 dark:hover:text-white', variant === 'danger' && 'bg-rose-600 text-white hover:bg-rose-700', size === 'sm' && 'h-8 rounded-md px-3 text-xs', size === 'md' && 'h-10 rounded-lg px-4 text-sm', size === 'lg' && 'h-12 rounded-lg px-5 text-sm', className)} {...props} />
}
export function Badge({ children, tone = 'neutral', className }: { children: ReactNode; tone?: 'neutral' | 'blue' | 'green' | 'amber' | 'purple'; className?: string }) {
  return <span className={cn('inline-flex items-center rounded-md px-2 py-1 text-[11px] font-semibold tracking-wide', tone === 'neutral' && 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300', tone === 'blue' && 'bg-blue-50 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300', tone === 'green' && 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300', tone === 'amber' && 'bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300', tone === 'purple' && 'bg-violet-50 text-violet-700 dark:bg-violet-950/50 dark:text-violet-300', className)}>{children}</span>
}
export function Card({ children, className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn('rounded-xl border border-line bg-white shadow-panel dark:border-slate-800 dark:bg-slate-900 dark:shadow-none', className)} {...props}>{children}</div> }
export function SectionTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="mb-5 flex items-end justify-between gap-4"><div>{eyebrow && <p className="mb-1 text-[11px] font-bold uppercase tracking-[0.16em] text-brand">{eyebrow}</p>}<h2 className="text-[19px] font-semibold tracking-tight text-ink dark:text-white">{title}</h2></div>{action}</div> }
